services:
  mongodb:
    image: mongo
    container_name: dwa-mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./volume-data:/data/db
    networks:
      - dwa-mongo-network

  mongo-express:
    image: mongo-express
    container_name: dwa-mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - dwa-mongo-network

networks:
  dwa-mongo-network:
    driver: bridge
    name: dwa-mongo-network
