services:
  mongo:
    image: mongo
    container_name: docs-mongodb
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./volume-data:/data/db
    networks:
      - docs-mongo-network

  mongo-express:
    image: mongo-express
    container_name: docs-mongo-express
    ports:
      - 8081:8081
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - docs-mongo-network

networks:
  docs-mongo-network:
    driver: bridge
    name: docs-mongo-network
